import daisyui from "daisyui";

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        accent: {
          DEFAULT: "#6D5DFB",
          hover: "#7C6CFF",
        },
      },
      fontFamily: {
        sans: ["Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
    },
  },
  plugins: [daisyui],
  daisyui: {
    themes: [
      {
        wireframe: {
          "color-scheme": "light",
          primary: "#6366f1",
          "primary-content": "#ffffff",
          secondary: "#ec4899",
          "secondary-content": "#ffffff",
          accent: "#f59e0b",
          "accent-content": "#18181b",
          neutral: "#3b0764",
          "neutral-content": "#ffffff",
          "base-100": "#faf5ff",
          "base-200": "#f3e8ff",
          "base-300": "#e9d5ff",
          "base-content": "#3b0764",
          info: "#0284c7",
          success: "#16a34a",
          warning: "#d97706",
          error: "#dc2626",
          fontFamily: 'Chalkboard, "Comic Sans MS", "Comic Neue", cursive, sans-serif',
          "--rounded-box": "0.5rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "0.5rem",
          "--tab-radius": "0.5rem",
        },
      },
      "night",
      "dark",
      "light",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "coffee",
      "winter",
      "dim",
      "nord",
      "sunset",
    ],
  },
};
