export const FEATURED_THEMES = [
  {
    name: "cupcake",
    label: "Cupcake [Aesthetic Pastel 🧁]",
    vibe: "Soft Pastel & Playful",
    colors: ["#faf7f5", "#65c3c8", "#ef9fbc", "#291334"],
  },
  {
    name: "light",
    label: "Light [Clean Minimal ☀️]",
    vibe: "Crisp & Modern Light",
    colors: ["#ffffff", "#5a67d8", "#8b5cf6", "#1a202c"],
  },
  {
    name: "wireframe",
    label: "Wireframe [Lavender Sketch Font ✏️💜]",
    vibe: "Electric Indigo & Lavender Palette + Sketch Font",
    special: true,
    colors: ["#faf5ff", "#6366f1", "#ec4899", "#3b0764"],
  },
  {
    name: "sunset",
    label: "Sunset [Warm Glow 🌅]",
    vibe: "Warm Evening Gradient",
    colors: ["#1e293b", "#f5734c", "#ec4899", "#ffffff"],
  },
  {
    name: "synthwave",
    label: "Synthwave [Neon Cyber 🌆]",
    vibe: "80s Neon Cyberpunk",
    colors: ["#2d1b69", "#e779c1", "#58c7f3", "#f8f8f2"],
  },
  {
    name: "dracula",
    label: "Dracula [Vampire Dark 🧛]",
    vibe: "Popular Vampire Accent",
    colors: ["#282a36", "#ff79c6", "#bd93f9", "#f8f8f2"],
  },
  {
    name: "forest",
    label: "Forest [Nature Green 🌲]",
    vibe: "Earthy & Fresh",
    colors: ["#1f1d1d", "#3ebc96", "#70c217", "#e2e8f0"],
  },
  {
    name: "retro",
    label: "Retro [Vintage Warm 📻]",
    vibe: "Warm Classic Paper",
    colors: ["#e4d8b4", "#ea6962", "#6aaa64", "#282425"],
  },
  {
    name: "night",
    label: "Night [Verba Dark (Default) 🌙]",
    vibe: "Linear & Raycast Slate",
    colors: ["#0a0a0b", "#6d5dfb", "#7c6cff", "#fafafa"],
  },
];

export const THEMES = [
  {
    name: "cupcake",
    label: "Cupcake [Aesthetic Pastel 🧁]",
    colors: ["#faf7f5", "#65c3c8", "#ef9fbc", "#291334"],
    featured: true,
  },
  {
    name: "light",
    label: "Light [Clean Minimal ☀️]",
    colors: ["#ffffff", "#5a67d8", "#8b5cf6", "#1a202c"],
    featured: true,
  },
  {
    name: "wireframe",
    label: "Wireframe [Lavender Sketch Font ✏️💜]",
    colors: ["#faf5ff", "#6366f1", "#ec4899", "#3b0764"],
    special: true,
    featured: true,
  },
  {
    name: "sunset",
    label: "Sunset [Warm Glow 🌅]",
    colors: ["#1e293b", "#f5734c", "#ec4899", "#ffffff"],
    featured: true,
  },
  {
    name: "synthwave",
    label: "Synthwave [Neon Cyber 🌆]",
    colors: ["#2d1b69", "#e779c1", "#58c7f3", "#f8f8f2"],
    featured: true,
  },
  {
    name: "dracula",
    label: "Dracula [Vampire Dark 🧛]",
    colors: ["#282a36", "#ff79c6", "#bd93f9", "#f8f8f2"],
    featured: true,
  },
  {
    name: "forest",
    label: "Forest [Nature Green 🌲]",
    colors: ["#1f1d1d", "#3ebc96", "#70c217", "#e2e8f0"],
    featured: true,
  },
  {
    name: "retro",
    label: "Retro [Vintage Warm 📻]",
    colors: ["#e4d8b4", "#ea6962", "#6aaa64", "#282425"],
    featured: true,
  },
  {
    name: "night",
    label: "Night [Verba Dark (Default) 🌙]",
    colors: ["#0a0a0b", "#6d5dfb", "#7c6cff", "#fafafa"],
    featured: true,
  },
  {
    name: "dark",
    label: "Dark",
    colors: ["#1f2937", "#8b5cf6", "#ec4899", "#1a202c"],
  },
  {
    name: "bumblebee",
    label: "Bumblebee",
    colors: ["#ffffff", "#f8e36f", "#f0d50c", "#1c1917"],
  },
  {
    name: "emerald",
    label: "Emerald",
    colors: ["#ffffff", "#66cc8a", "#3b82f6", "#1e3a8a"],
  },
  {
    name: "corporate",
    label: "Corporate",
    colors: ["#ffffff", "#4b6bfb", "#7b92b2", "#1d232a"],
  },
  {
    name: "cyberpunk",
    label: "Cyberpunk",
    colors: ["#ffee00", "#ff7598", "#75d1f0", "#1a103d"],
  },
  {
    name: "valentine",
    label: "Valentine",
    colors: ["#f0d6e8", "#e96d7b", "#a991f7", "#37243c"],
  },
  {
    name: "halloween",
    label: "Halloween",
    colors: ["#0d0d0d", "#ff7800", "#006400", "#ffffff"],
  },
  {
    name: "garden",
    label: "Garden",
    colors: ["#e9e7e7", "#ec4899", "#16a34a", "#374151"],
  },
  {
    name: "aqua",
    label: "Aqua",
    colors: ["#193549", "#4cd4e3", "#9059ff", "#f8d766"],
  },
  {
    name: "lofi",
    label: "Lofi",
    colors: ["#0f0f0f", "#1a1919", "#232323", "#2c2c2c"],
  },
  {
    name: "pastel",
    label: "Pastel",
    colors: ["#f7f3f5", "#d1c1d7", "#a1e3d8", "#4a98f1"],
  },
  {
    name: "fantasy",
    label: "Fantasy",
    colors: ["#ffe7d6", "#a21caf", "#3b82f6", "#f59e0b"],
  },
  {
    name: "black",
    label: "Black",
    colors: ["#000000", "#191919", "#313131", "#4a4a4a"],
  },
  {
    name: "luxury",
    label: "Luxury",
    colors: ["#171618", "#1e293b", "#94589c", "#d4a85a"],
  },
  {
    name: "cmyk",
    label: "CMYK",
    colors: ["#f0f0f0", "#0891b2", "#ec4899", "#facc15"],
  },
  {
    name: "autumn",
    label: "Autumn",
    colors: ["#f2f2f2", "#8c1f11", "#f28c18", "#6f4930"],
  },
  {
    name: "business",
    label: "Business",
    colors: ["#f5f5f5", "#1e40af", "#3b82f6", "#f97316"],
  },
  {
    name: "acid",
    label: "Acid",
    colors: ["#110e0e", "#ff00f2", "#ff7a00", "#99ff01"],
  },
  {
    name: "lemonade",
    label: "Lemonade",
    colors: ["#ffffff", "#67e8f9", "#f5d742", "#2c3333"],
  },
  {
    name: "coffee",
    label: "Coffee",
    colors: ["#20161f", "#dd9866", "#497174", "#eeeeee"],
  },
  {
    name: "winter",
    label: "Winter",
    colors: ["#ffffff", "#0284c7", "#d946ef", "#0f172a"],
  },
  {
    name: "dim",
    label: "Dim",
    colors: ["#1c1c27", "#10b981", "#ff5a5f", "#0f172a"],
  },
  {
    name: "nord",
    label: "Nord",
    colors: ["#eceff4", "#5e81ac", "#81a1c1", "#3b4252"],
  },
];

export const LANGUAGES = [
  "English",
  "Telugu",
  "Hindi",
  "Spanish",
  "French",
  "German",
  "Mandarin",
  "Japanese",
  "Korean",
  "Tamil",
  "Bengali",
  "Russian",
  "Portuguese",
  "Arabic",
  "Italian",
  "Turkish",
  "Dutch",
  "Vietnamese",
  "Polish",
  "Swedish",
  "Marathi",
  "Kannada",
  "Malayalam",
  "Punjabi",
  "Urdu",
  "Greek",
  "Indonesian",
  "Thai",
];

export const LANGUAGE_TO_FLAG = {
  english: "gb",
  telugu: "in",
  hindi: "in",
  spanish: "es",
  french: "fr",
  german: "de",
  mandarin: "cn",
  japanese: "jp",
  korean: "kr",
  tamil: "in",
  bengali: "bd",
  russian: "ru",
  portuguese: "pt",
  arabic: "sa",
  italian: "it",
  turkish: "tr",
  dutch: "nl",
  vietnamese: "vn",
  polish: "pl",
  swedish: "se",
  marathi: "in",
  kannada: "in",
  malayalam: "in",
  punjabi: "in",
  urdu: "pk",
  greek: "gr",
  indonesian: "id",
  thai: "th",
};
